version: 0.0.{build}
branches:
  only:
    - master
environment:
  EXPO_CLI_PASSWORD:
    secure: eC6bd8l9jI05cWxELNZ6qg==
  expo_username:
    secure: FWNebo+rTRr+aRiCen/vog==
hosts:
  Drunk Diary: 160.85.252.71
build:
  verbosity: detailed
test_script:
  # Install dependencies
  - npm install
  # Output useful info for debugging.
  - node --version
  - npm --version
deploy_script:
    # Raising inotify limit temporarily so ubuntu doesn't crash
  - sudo sysctl fs.inotify.max_user_watches=524288 && sudo sysctl -p
  # Deploy on expo
  - npx expo login --non-interactive -u $expo_username
  - npx expo publish --non-interactive

